name: weatherly
description: Weather Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  auto_route: ^7.9.1
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  freezed: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
